### ISSUE TITLE
报‘length’,403错误怎么解决啊？

### ISSUE THREAD

**Issue by duang-duang1010** [sesine/wechat-weapp-movie#46]
GET https://sesine.com/mina/api/movie/top250?city=%E6%9D%AD%E5%B7%9E&start=0&count=20 403 (Forbidden)
VM507:1 thirdScriptError
Cannot read property 'length' of undefined;at api request success callback function
TypeError: Cannot read property 'length' of undefined
    at success (http://127.0.0.1:26796/appservice/comm/script/fetch.js:25:31)
    at http://127.0.0.1:26796/appservice/appservice?t=1573026504979:9:21074
    at t.success (http://127.0.0.1:26796/appservice/appservice?t=1573026504979:9:16546)
    at Function.o.(anonymous function) (http://127.0.0.1:26796/appservice/__dev__/WAService.js:1:1182257)
    at http://127.0.0.1:26796/appservice/__dev__/WAService.js:1:108166
    at C (http://127.0.0.1:26796/appservice/__dev__/WAService.js:1:439731)
    at i.<anonymous> (http://127.0.0.1:26796/appservice/__dev__/WAService.js:1:739717)
    at i.emit (http://127.0.0.1:26796/appservice/__dev__/WAService.js:1:486637)
    at Ci (http://127.0.0.1:26796/appservice/__dev__/WAService.js:1:740355)
    at http://127.0.0.1:26796/appservice/__dev__/WAService.js:1:741576

**Comment by ChunYangFu** [comment]
兄弟 这个界面接口这个怎么解决

**Comment by Roll-to-tomorrow** [comment]
你好，你解决这个问题了吗，我最及也在调这个，怎么解决呢

**Comment by hongkai04** [comment]
同+1

**Comment by GardeniaWhite** [comment]
同样报错+1
